baseURL = 'https://zverevzve.github.io/YUMSH-site/'
languageCode = 'ru-ru'
title = 'Юношеская Математическая Школа'
theme = "quint"
summaryLength = 20                  # Number of characters in your card summaries

[params]
useToc = true
description = 'Demo site for the Hugo theme Quint.'

[markup.goldmark.renderer]
unsafe = true

[[module.imports]]
path = "github.com/privatemaker/headless-cms"

[outputs]
home = [ "HTML", "RSS", "HeadlessCMSConfig" ]

[params.headless_cms]
engine = "decap"
site_url = "https://zverevzve.github.io/YUMSH-site/"

